# Generated by Django 4.0.5 on 2022-06-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adrress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adrress',
        ),
    ]
