# Generated by Django 4.0.5 on 2022-06-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_adrress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
